### ISSUE TITLE
Review all the sizes for App Store

### ISSUE THREAD

**Issue by luisherranz** [worona/publish-native-app-extension-worona#17]
At least `Icon-83.5@2x.png` is missing.

https://developer.apple.com/library/content/qa/qa1686/_index.html

![screen shot 2017-02-23 at 18 29 53](https://cloud.githubusercontent.com/assets/3305402/23270993/1e324bf4-f9f6-11e6-8f6f-b3528dca15ee.png)

**Comment by Poliuk** [comment]
Another user is pointing out this issue: 

> When you turn the ipad horizontal, it shows the phonegap logo

![screen shot 2017-05-16 at 12 47 46](https://cloud.githubusercontent.com/assets/2798729/26102599/ef28805a-3a35-11e7-96dd-e1ea5900437d.png)
![screen shot 2017-05-16 at 12 47 51](https://cloud.githubusercontent.com/assets/2798729/26102598/ef23ffc6-3a35-11e7-8adb-236f84adfcb7.png)

**Comment by Poliuk** [comment]
Another user with the same request:

> Worona doesnt generate these Screen/App icons PNGs : 
> AppIcon83.5x83.5
> LaunchImage-700-Landscape@2x ipad
> LaunchImage-700-LandScape ipad
> LaunchImage-800-Landscape-736h@3x
> These iCons/Start Screen Images are needed when people use The App with an iPad cross.

**Comment by Poliuk** [comment]
Notify once we fix this: https://secure.helpscout.net/conversation/352580800/4991/?folderId=679562
